In [1]:
import torch
from torch.autograd.function import InplaceFunction, Function
import torch.nn as nn
import torch.nn.functional as F
import math

In [9]:
Input = torch.Tensor([2.1])

In [10]:
Input.clamp_(0, 5).round_()

tensor([2.])

In [12]:
a = torch.rand(20,10,3)

In [18]:
a.view(a.size(0),-1).min(-1)

(tensor([0.1143, 0.0202, 0.0626, 0.0347, 0.0578, 0.0032, 0.0907, 0.0410, 0.0370,
         0.0522, 0.0041, 0.1042, 0.0102, 0.0070, 0.0128, 0.0366, 0.0298, 0.0051,
         0.0244, 0.0171]),
 tensor([13, 14,  3,  8,  6,  2,  8, 20,  8,  6, 17, 17, 19,  6, 15, 19, 26, 25,
         29, 18]))

In [19]:
a.shape

torch.Size([20, 10, 3])

In [23]:
y = a.view(a.shape[0]//20,-1)

In [25]:
y.size()

torch.Size([1, 600])

In [28]:
y.min(-1)[0].mean(-1)

tensor(0.0032)

In [29]:
conv_layer = nn.Conv2d(3, 5, kernel_size=3, stride=1,
                     padding=1, bias=False)

In [30]:
conv_layer.weight.size()

torch.Size([5, 3, 3, 3])